name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        run: env | grep -i github
      - name: Build
        run: |
          echo "docker-compose build"
          echo 'docker-compose run -e "NODE_ENV=test" jpm node index.js'
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: PullRequest
        id: get_pull_request
        uses: octokit/request-action@v2.0.2
        with:
          route: GET /repos/:owner/:repo/pulls
          owner: "msimmons"
          repo: "jpm"
          state: "open"
          head: "msimmons:test-actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: octokit/request-action@v2.0.2
      #   id: create_deployment
      #   with:
      #     route: POST /repos/:owner/:repo/deployments
      #     owner: "msimmons"
      #     repo: "jpm"
      #     ref: "test-actions"
      #     task: "deploy"
      #     auto_merge: false
      #     required_contexts: "[]"
      #     payload: '{"key1": "value1", "key2": 3}'
      #     environment: "sbox0"
      #     description: "Not sure what to say here"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: EchoIt
        run: echo ${{ steps.get_pull_request.outputs }}
  