name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ShowEnv
        run: env
      - name: DoIt
        run: |
          docker-compose build
          docker-compose run -e "NODE_ENV=test" jpm node index.js
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: PublishIt
        run: |
          docker-compose --version
          docker --version
          docker images
