name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        run: env
      - name: Build
        run: |
          docker-compose build
          docker-compose run -e "NODE_ENV=test" jpm node index.js
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: PublishIt
        run: |
          docker-compose --version
          docker --version
          docker images
      - uses: octokit/request-action@v2.0.2
        id: create_deployment
        with:
          route: POST /repos/:owner/:repo/deployments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          task: "deploy"
          auto_merge: false
          payload: '{"key1": "value1", "key2": 3}'
          environment: "sbox0"
          description: "Not sure what to say here"
          transient_environment: true
          production_environment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  