name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        run: env | grep -i github
      - name: Timestamp
        run: |
          echo `date +%Y%m%d`
          echo "TAG_TS=`date +%Y%m%d`" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "the tag would be ${TAG_TS}-${GITHUB_RUN_NUMBER}"
      - name: Docker Login
        run: docker login https://docker.pkg.github.com -u msimmons -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        run: docker build -t docker.pkg.github.com/msimmons/jpm/jpm-test:latest .
      - name: Docker Push
        run: docker push docker.pkg.github.com/msimmons/jpm/jpm-test:latest
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker Login
        run: docker login https://docker.pkg.github.com -u msimmons -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Pull
        run: docker pull docker.pkg.github.com/msimmons/jpm/jpm-test:latest
      - name: List
        run: docker run --rm docker.pkg.github.com/msimmons/jpm/jpm-test:latest ls
      - name: PullRequest
        id: get_pull_request
        uses: octokit/request-action@v2.0.2
        with:
          route: GET /repos/:owner/:repo/pulls
          owner: "msimmons"
          repo: "jpm"
          state: "open"
          head: "msimmons:test-actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-passing-data:
    uses: ./.github/workflows/manual.yaml
    with:
      tag: 1234
      stack: sbox0