name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: DoIt
        run: npm --version
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: PublishIt
        run: |
          docker-compose --version
          docker --version