name: Manual
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to deploy"
        required: true
      stack:
        description: "The stack to deploy to"
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - echo-command: echo "This is one thing"
           migrate-command: echo "migrate something"
           test-command: echo "test something"
         - echo-command: echo "This is another thing"
           migrate-command: echo "migrate something else"
           test-command: echo "test something else"
    steps:
    - run: |
        ${{ matrix.echo-command }}
        ${{ matrix.migrate-command }}
        ${{ matrix.test-command }}